[package]
name = "auto_uds"
version = "0.5.5"
description = "DEPRECATED: The new crate name automotive_diag."
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>", "Ashcon Mohseninia <ashconm@outlook.com>"]
repository = "https://github.com/nyurik/automotive_diag"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["uds", "iso14229", "iso_14229_1", "automotive", "no_std"]
categories = ["embedded", "no-std", "encoding", "parsing"]

[features]
default = ["std"]
std = []

[dependencies]
enum2repr = "0.1"

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }
