[package]
name = "automotive_diag"
version = "0.1.8"
description = "Core definitions for various Automotive ECU Diagnostics such as UDS ISO-14229, KWP2000, OBD-II, etc."
authors = ["Yuri Astrakhan <YuriAstrakhan@gmail.com>", "Ashcon Mohseninia <ashconm@outlook.com>"]
repository = "https://github.com/nyurik/automotive_diag"
edition = "2021"
license = "MIT OR Apache-2.0"
keywords = ["uds", "kwp2000", "obd", "automotive", "no_std"]
categories = ["embedded", "no-std", "encoding", "parsing"]
rust-version = "1.61.0"

[features]
default = ["std", "display", "with-kwp2000", "with-obd2", "with-uds"]
# Include support for std library. Without this feature, uses `no_std` attribute
std = []
# Add Display implementation for all enums, using doc comments as display strings
display = ["dep:displaydoc"]
# Include support for Keyword protocol 2000 - ISO142330
with-kwp2000 = []
# Include support for On-board diagnostics
with-obd2 = []
# Include support for Unified Diagnostic Services
with-uds = []

[dependencies]
enum2repr = "0.1"
displaydoc = { version = "0.2", optional = true }

[dev-dependencies]
cargo-husky = { version = "1", features = ["user-hooks"], default-features = false }

[lints.rust]
unsafe_code = "forbid"
unused_qualifications = "warn"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
module_name_repetitions = "allow"
